baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Trys Mudford"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
footnoteReturnLinkContents = "â†©"
[markup.goldmark.renderer]
  unsafe= true